name: Build and Deploy

on:
  push:
    branches:
      - DEV
      - STAGING
      - PROD

env:
  IMAGE_NAME: phwebcloud/python_app
  DOCKER_REGISTRY: ghcr.io  # GitHub Container Registry

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout o código da branch
      - name: Checkout Code
        uses: actions/checkout@v3

      # Configuração do Node.js (se necessário para dependências)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Instala dependências (exemplo para Python e Node.js)
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          npm install

      # Realiza os testes
      - name: Run Tests
        run: pytest tests/

  docker-build:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      # Checkout o código
      - name: Checkout Code
        uses: actions/checkout@v3

      # Login no GitHub Packages
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login $DOCKER_REGISTRY -u ${{ github.actor }} --password-stdin

      # Construção da imagem Docker com tag
      - name: Build Docker Image
        run: |
          docker build -t $DOCKER_REGISTRY/${{ github.repository }}/$IMAGE_NAME:${{ github.sha }} .
          docker tag $DOCKER_REGISTRY/${{ github.repository }}/$IMAGE_NAME:${{ github.sha }} $DOCKER_REGISTRY/${{ github.repository }}/$IMAGE_NAME:latest

      # Push da imagem Docker para o GitHub Packages
      - name: Push Docker Image
        run: |
          docker push $DOCKER_REGISTRY/${{ github.repository }}/$IMAGE_NAME:${{ github.sha }}
          docker push $DOCKER_REGISTRY/${{ github.repository }}/$IMAGE_NAME:latest

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      # Deploy baseado na branch
      - name: Deploy to Environment
        run: |
          if [[ "${{ github.ref_name }}" == "DEV" ]]; then
            echo "Deploying to DEV"
            # Comandos de deploy para DEV
          elif [[ "${{ github.ref_name }}" == "STAGING" ]]; then
            echo "Deploying to STAGING"
            # Comandos de deploy para STAGING
          elif [[ "${{ github.ref_name }}" == "PROD" ]]; then
            echo "Deploying to PROD"
            # Comandos de deploy para PROD com estratégias como Blue-Green
          fi
